import type { Config } from 'tailwindcss';

export const tailwindTheme: NonNullable<Config['theme']>['extend'] = {
  colors: {
    sb: {
      navy: 'var(--sb-navy)',
      'navy-pressed': 'var(--sb-navy-pressed)',
      'navy-tint': 'var(--sb-navy-tint)',
      white: 'var(--sb-white)',
      bg: 'var(--sb-bg)',
      border: 'var(--sb-border)',
      ink: 'var(--sb-ink)',
      'ink-2': 'var(--sb-ink-2)',
      'ink-3': 'var(--sb-ink-3)',
      verified: 'var(--sb-verified)',
      'verified-ink': 'var(--sb-verified-ink)',
      'verified-tint': 'var(--sb-verified-tint)',
      review: 'var(--sb-review)',
      'review-ink': 'var(--sb-review-ink)',
      'review-tint': 'var(--sb-review-tint)',
      critical: 'var(--sb-critical)',
      'critical-ink': 'var(--sb-critical-ink)',
      'critical-tint': 'var(--sb-critical-tint)',
      scrim: 'var(--sb-scrim)',
    },
  },
  spacing: {
    'sb-1': 'var(--sb-space-1)',
    'sb-2': 'var(--sb-space-2)',
    'sb-3': 'var(--sb-space-3)',
    'sb-3.5': 'var(--sb-space-3-5)',
    'sb-4': 'var(--sb-space-4)',
    'sb-5': 'var(--sb-space-5)',
    'sb-6': 'var(--sb-space-6)',
    'sb-7': 'var(--sb-space-7)',
    'sb-8': 'var(--sb-space-8)',
  },
  borderRadius: {
    sheet: 'var(--sb-radius-sheet)',
    card: 'var(--sb-radius-card)',
    tile: 'var(--sb-radius-tile)',
    thumb: 'var(--sb-radius-thumb)',
    pill: 'var(--sb-radius-pill)',
  },
  boxShadow: {
    e1: 'var(--sb-shadow-e1)',
    e2: 'var(--sb-shadow-e2)',
    e3: 'var(--sb-shadow-e3)',
  },
  fontFamily: {
    ui: ['var(--font-ui)', 'sans-serif'],
    mono: ['var(--font-mono)', 'monospace'],
    hero: ['var(--font-hero-num)', 'sans-serif'],
  },
  fontSize: {
    'num-xl': ['44px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
    'num-l': ['34px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '600' }],
    'display-thin': ['32px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '300' }],
    'title-1': ['24px', { lineHeight: '30px', letterSpacing: '-0.015em', fontWeight: '700' }],
    'title-2': ['22px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
    'title-3': ['17px', { lineHeight: '22px', letterSpacing: '-0.01em', fontWeight: '600' }],
    body: ['15px', { lineHeight: '22px', letterSpacing: '0', fontWeight: '400' }],
    callout: ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '500' }],
    caption: ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '400' }],
    'caption-500': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '500' }],
    'panel-label': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
    'mono-m': ['13px', { lineHeight: '18px', letterSpacing: '0', fontWeight: '500' }],
    'mono-s': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '500' }],
  },
};
